version: '2'
services:
  api:
    build: api/
    command: /startup/prod-entrypoint.sh
    restart: on-failure
    volumes:
      - static-files:/code/static-files
      - site-media:/code/site-media
    depends_on:
      - db
    env_file:
      env_prod.list
  node:
    build: frontend/
    command: npm start
    depends_on:
      - api
    env_file:
      env_prod.list
  db:
    image: mariadb
    env_file:
      env_prod.list
  nginx:
    build: nginx/
    command: ./start.sh
    ports:
      - "8000:80"
    volumes:
      - static-files:/var/www/html/openeats-static/static-files
      - site-media:/var/www/html/openeats-static/site-media
    depends_on:
      - api
      - node
    env_file:
      env_prod.list
volumes:
  database:
  static-files:
  site-media:
